name: CI

on: 
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    fail-fast: false
    strategy:
      matrix: 
        node: [4, 5, 6, 7, 8]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: |
        npm install
        npm install -g grunt-cli
        grunt build:travis
